name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  release-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85.0
          components: rustfmt, clippy
      - uses: taiki-e/install-action@just
      - name: Run release gate
        run: just release
